/** Marki rozpoznawane w trybie regex (kolejność: dłuższe nazwy pierwsze) */
export const PARSER_VEHICLE_MAKES = [
  'Mercedes-Benz',
  'Alfa Romeo',
  'Land Rover',
  'Harley-Davidson',
  'Renault Trucks',
  'Volkswagen',
  'Suzuki',
  'Toyota',
  'Honda',
  'Mazda',
  'BMW',
  'Audi',
  'Ford',
  'Opel',
  'Fiat',
  'Seat',
  'Skoda',
  'Volvo',
  'Nissan',
  'Mitsubishi',
  'Hyundai',
  'Kia',
  'Peugeot',
  'Renault',
  'Citroen',
  'Dacia',
  'Subaru',
  'Kawasaki',
  'Yamaha',
  'Ducati',
  'Aprilia',
  'KTM',
  'Triumph',
  'Scania',
  'MAN',
  'DAF',
  'Iveco',
] as const;

/** Typowe modele — ułatwiają wyciągnięcie modelu po marce z tekstu */
export const PARSER_MODELS_BY_MAKE: Record<string, string[]> = {
  Suzuki: ['Samurai', 'Swift', 'Vitara', 'Jimny', 'Ignis', 'SX4', 'Baleno'],
  BMW: ['E30', 'E46', 'E90', 'F10', 'F30', 'X3', 'X5', 'Seria 3', 'Seria 5'],
  Volkswagen: ['Golf', 'Passat', 'Polo', 'Tiguan', 'Touran', 'Transporter'],
  Ford: ['Focus', 'Mondeo', 'Fiesta', 'Kuga', 'Transit'],
  Audi: ['A3', 'A4', 'A6', 'A8', 'Q3', 'Q5', 'Q7'],
  Toyota: ['Corolla', 'Avensis', 'Yaris', 'RAV4', 'Hilux'],
  Opel: ['Astra', 'Vectra', 'Corsa', 'Insignia', 'Zafira'],
  'Mercedes-Benz': ['A-Klasse', 'C-Klasse', 'E-Klasse', 'Sprinter'],
};
